version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "monday"
  reviewers:
    - "LukasHirt"
  labels:
    - "Status:Needs-Review"
    - "Topic:Dependencies"
