---
_extends: gh-labels

repository:
  name: web
  description: :dragon_face: Next generation frontend for ownCloud X and Infinite Scale
  homepage: https://owncloud.github.io/clients/web/
  has_wiki: false

labels:
  - name: Topic:Accessibility
    oldname: Accessibility
    color: "#ccf4ff"
  - name: Topic:Extensions-framework
    oldname: extensions framework
    color: "#ccf4ff"
  - name: PM prio 1
    color: fbca04
  - name: PM prio 2
    color: fbca04
  - name: PM prio 3
    color: fbca04
  - name: QA
    color: 1d76db
  - name: QA-blocker
    color: 0052cc
  - name: QA-known
    color: 0052cc
  - name: QA-ready
    color: 0052cc
  - name: QA-team
    color: 4cc948
  - name: QA-testing
    color: 0052cc
  - name: Sys Admin
    color: ededed
  - name: WIP
    color: 8c8cea
  - name: Waiting
    color: e6e6e6
  - name: Waiting Internal
    color: e6e6e8
  - name: Waiting On Review/Feedback
    color: ededed
  - name: bounty
    color: 129e5e
  - name: browser:chrome
    color: 207de5
  - name: browser:edge
    color: 207de5
  - name: browser:firefox
    color: 207de5
  - name: browser:ie
    color: 207de5
  - name: browser:safari
    color: 207de5
  - name: bug
    color: fc2929
  - name: bug-analysis
    color: fbca04
  - name: bug-solved
    color: 0e8a16
  - name: clarification request
    color: d4c5f9
  - name: core-bug
    color: ededed
  - name: credits
    color: e58729
  - name: dependencies
    color: 0025ff
  - name: design
    color: cc317c
  - name: discussion
    color: fbca04
  - name: documentation
    color: BFDADC
  - name: feature:files
    color: d4c5f9
  - name: feature:markdown-editor
    color: d4c5f9
  - name: feature:pdf-viewer
    color: d4c5f9
  - name: feature:collaborators
    color: d4c5f9
  - name: feature:media-viewer
    color: d4c5f9
  - name: in progress
    color: ededed
  - name: invalid
    color: ededed
  - name: junior job
    color: f6d300
  - name: needs info
    color: 0b02e1
  - name: orga
    color: c5def5
  - name: overview
    color: fef2c0
  - name: p1-urgent
    color: fc2929
  - name: p2-high
    color: fc2929
  - name: p3-medium
    color: fc2929
  - name: p4-low
    color: fc2929
  - name: packaging
    color: F7C6C7
  - name: performance
    color: fbca04
  - name: ready
    color: ededed
  - name: regression
    color: e11d21
  - name: release note
    color: BFD4F2
  - name: research
    color: FFFF00
  - name: review carefully!
    color: ededed
  - name: security
  - name: settings:admin
    color: 02d7e1
  - name: technical debt
    color: FFFF00
  - name: tested
    color: FBCA04
  - name: won't fix
    color: ffffff
